name: WeatherControl
main: net.craftrepo.WeatherControl.weathercontrol
version: 1.2.0
commands:
    lightningpick:
        description: toggle your pick to start lightning
        usage: |
               /<command>
    strikeplayer:
        description: strike a user with lightning
        usage: |
               /<command> {target}
    strikepig:
        description: strike a pig with lightning
        usage: |
               /<command> [radius]
    strikecreeper:
        description: strike a creeper with lightning
        usage: |
               /<command> [radius]
    lightningstrike:
        description: strike down lightning on what ever block you are looking
        usage: |
               /<command>
    startstorm:
        description: Start a lightning storm
        usage: |
               /<command> [duration]
    startrain:
        description: Start a rain/snow storm
        usage: |
               /<command> [duration]
    stoprain:
       description: Stop a rain/snow storm
       aliases: ['stopstorm']
       usage: |
               /<command>
    strikerow:
        description: Strike a row of lightning in the diraction you are facing strting form the block you are looking at.
        usage: |
               /<command> [range]